path: C:\\Users\\user\\OneDrive\\Desktop\\Staff_Detection\\data # dataset root dir
train: images/train # train images (relative to 'path')
val: images/val # val images (relative to 'path')

# Classes
names:
  0: staff